name: Create Mod Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Zip Archive
        run: |
          ls -la 
          mkdir EquipManager-HSK
          cp -r About/ Common/ 1.5/ EquipManager-HSK/
          zip -r EquipManager-HSK.zip EquipManager-HSK/

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: EquipManager-HSK.zip
          token: ${{ secrets.GITHUB_TOKEN }}
